services:
  sms:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5220:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - .data:/usr/src/app/.data

volumes:
  .data:
  node_modules:

